---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: local-ccm
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:local-ccm
rules:
# Permissions to get and update nodes
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch", "patch"]
# Permissions to update node status (for addresses)
- apiGroups: [""]
  resources: ["nodes/status"]
  verbs: ["patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:local-ccm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:local-ccm
subjects:
- kind: ServiceAccount
  name: local-ccm
  namespace: kube-system
