{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "local-ccm.serviceAccountName" . }}
  labels:
    {{- include "local-ccm.labels" . | nindent 4 }}
{{- end }}
